@extends('job_board_layout.app')
@section('content')
@if ($updated = Session::get('posted'))
<div class="alert alert-success alert-block mb-0 text-center">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>{{ $updated }}</strong>
</div>
@endif
@php
// $items=0;
  $boringLanguage = 'fr';
$translator = \Carbon\Translator::get($boringLanguage);

$date1 = Carbon\Carbon::now();
$translator->setTranslations([
    'after' => function ($time) {
        return 'publié'.' '.''.$time.' avant';
    },
]);
@endphp

@if ($success = Session::get('success'))
<div class="alert alert-success alert-block mb-0 text-center">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>{{ $success }}</strong>
</div>
@endif


<div class="container-fluid job_listing_featured_image">
  <div class="container h-100 ">
    <div class="row h-100 align-content-center">
        <h1 class="first-heading text-center">Recherche d’emploi</h1>
      <div class="col-lg-12  d-flex ">

        <section class="search-form align-items-center">
          <form action="{{route('search',$job_seeker->id)}}" method="GET" class=" job_listing_form_search">
             
            <p class="inp-wrap search-wrap col-12 col-sm-12 col-md-12 col-lg-4 p-0">
              <input type="search" name="search_tag" id="search-field" class="grid"
                placeholder="e.g. pizza, pet supplies" />
            </p>
            <p class="inp-wrap cat-wrap col-10 col-sm-12 col-md-12 col-lg-4 p-0">
              <select name="search_category" id="categories" class="grid">
                <option value="0" disabled selected> fonction </option>
                @foreach($categories as $categorie)
                <option value="{{$categorie->id}}">{{$categorie->Name}}</option>
                @endforeach
              </select>
              <span class="sec2 d-none d-lg-block"></span>
              <span class="arow d-none d-sm-block"><i class="fa fa-angle-down"></i></span>
            </p>
            <p class="inp-wrap cat-wrap col-12 col-sm-12 col-md-12 col-lg-4 p-0">
              <select name="search_location" tabindex="-1" id="locations" class="grid">
                <option value="0" disabled selected>ville</option>

                @foreach ($locations as $location)

                <option value="{{$location->id}}">
                  {{$location->Name}}
                </option>
                @endforeach

              </select>
              <span class="sec1 d-none d-lg-block"></span>
              <span class="arow d-none d-sm-block"><i class="fa fa-angle-down"></i></span>
            </p>

            <p class="inp-wrap submit-wrap grid col-12 col-sm-12 col-md-12 col-lg-4 p-0">
              <button class="search-button btn" href="#ex1">
                <!-- Generated by IcoMoon.io -->
                {{-- <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"> --}}
                <span>Rechercher</span>
                <span><i class="fa fa-search"></i></span>
              </button>

            </p>
          </form>
        </section>

      </div>
      <div class="col-lg-12">
        <h4 class="caption"> Trouvez l'emploi que vous méritez</h4>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class=" col-md-4 col-lg-4  ">
      <div class="filters">
        <div class="select-header">
          <div>
            <span class="font-weight-bold">your selected</span>
            <hr class="selected d-none d-xl-block">
          </div>
          <div>
            <a href="" class="save">save</a>
            <a href="" class="clear">clear all</a>
          </div>
        </div>
        <div class="choose mt-5">
          <ul class="list-group list-selected ">
            <ul>
              {{-- <li>full time <i class="fa fa-window-close"></i></li> --}}

            </ul>
           
            <hr class="select-divider">
            <ul class="jobs-category-selected">
              {{-- <li>comptabilité <i class="fa fa-window-close"></i></li> --}}

            </ul>
            
          </ul>
        </div>
        <div class="categorie mt-5">
          <span class="font-weight-bold">categorie</span>
          <hr class="selected">
          <div class="input-group mt-5">
            {{-- <input type="text" class="form-control filter" data-search placeholder="Search Keywords"
              aria-label="Recipient's username" aria-describedby="basic-addon2" > --}}
            {{-- <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="button"><i class="fa fa-search"></i></button>
            </div> --}}
          </div>
        </div>
        <div class="job_categorie">

          <ul class="jobs">
            <ul class="p-0">
              {{-- @foreach ($categories as $categorie)
              <li>
              <form class="jobs-name" method="GET" action="{{route('search',$job_seeker->id)}}">
                  <div class="custom-control custom-checkbox" data-filter-item data-filter-name="{{$categorie->Name}}">
                    <input type="checkbox" class="custom-control-input search_categories"  onclick="submit()"  id="{{$categorie->id}}"
                          value="{{$categorie->id}}" name="search_category">
                    <label class="custom-control-label" for="{{$categorie->id}}">{{$categorie->Name}}</label>
                  </div>
                <span data-filter-item data-filter-name="{{$categorie->Name}}"> {{$categorie->job_offer->count()}}</span>
                </form>
              </li>
              @endforeach --}}
           
             
              @if(count($items) > 0)
              <section class="articles">
                  @include('job_seeker.pagination_data')
              </section>
              @endif
            </ul>
          </ul>
          {{-- <div class="d-flex justify-content-center">
            {!! $categories->links() !!}
          </div> --}}
        </div>
        {{-- <div class="salary mt-5">
          <span>
            salary
            <hr class="selected">
          </span>
          <div class="job_categorie mt-5 container">
            <ul class="jobs">
              <ul class="p-0">
                @foreach($salaries as $salary)
                <li>
                  <form>
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="{{$salary->id}}" name="search_salary">
                      <label class="custom-control-label" for="{{$salary->salary_label}}">{{$salary->Name}}</label>
                    </div>
                  </form>
                  <hr class="select-divider">
                </li>
                @endforeach
              </ul>
            </ul>
          </div>

        </div>
        <span>
          Location
          <hr class="selected">
        </span> --}}
        <div class="job_categorie mt-5">
          <ul class="jobs">
            <ul class="p-0">
              {{-- @foreach ($locations as $location)
              <li>
                <form class="jobs-name">
                  <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="{{$location->label}}"
                      name="search_location">
                    <label class="custom-control-label" for="{{$location->label}}">{{$location->Name}}</label>
                  </div>
                  <span>0</span>
                </form>
              </li>
              <hr class="select-divider">
              @endforeach --}}
            </ul>
          </ul>
        </div>
      </div>
    </div>
    <div class=" offset-lg-1">
    </div>
    <div class="jobs-render col-md-8 col-lg-7">
      {{-- <div class=" col-md-8 col-lg-7"> --}}
        <div class="jobs-header filters">
          <div class="jobs-display">
            <div class="icons-display d-none d-lg-flex">
  
              <span class="icon-display-jobs"><img src="{{asset('img/grid-1.png')}}" width="20px" alt=""></span>
              <span class="icon-display-jobs"><img src="{{asset('img/grid-1.png')}}" width="20px" alt=""></span>
              <span class="icon-display-jobs"><img src="{{asset('img/grid-1.png')}}" width="20px" alt=""></span>
            </div>
            {{-- <div class="notif">
              <span class="notif-bel"><i class="fa fa-bell"></i></span>
              <span>
  
                  <a href="" class="btn btn-default btn-rounded launch-button" data-toggle="modal" data-target="#modalRegisterForm">Launch
                    Modal Register Form</a>
                </span>
            </div> --}}
          </div>
          <div class="jobs-count">
            {{$count}} offres valables
          </div>
        </div>
  
        @if(!empty($failed))
        <div class="alert alert-danger mt-5"> {{ $failed }}</div>
        @endif
  @component('layouts.components.pop_up_form')
  @endcomponent
  {{-- @include('job_seeker.demo') --}}
        @foreach($job_offers as $job_offer)
        <div class="job-list-display filters ">
          <div class="job-img">
            <div>
            <img style="width: 250px;height: 150px;" src="{{asset('img/'.$job_offer->offer_image)}}">
            </div>
            <form action="{{route('show/single_offer',['id'=>$job_seeker->id,'offer_id'=>$job_offer->id])}}" method="GET">
            <button class="btn submit_job">
              <!-- Generated by IcoMoon.io -->
              {{-- <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"> --}}
              <span>postuler </span>
            </button>
          </form>
          </div>
          <div class="job-content">
            <span class="job-accesible text-danger">
              {{$job_offer->type_emploi}}
            </span>
            <span class="job-title font-weight-bold ">
              {{$job_offer->offer_title}}
            </span>
            <p class="job_description">
                {!!$job_offer->description!!}
            </p>
            <span class="apply-date">
              {{$date1->locale($boringLanguage)->diffForHumans($job_offer->created_at)}}
          </span>
  
            <div class="location">
              <span class="city"><i class="fa fa-flag"></i> {{$job_offer->location->Name}}</span>
              <span class="country"><i class="fa fa-location-arrow"></i> {{$job_offer->category->Name}}</span>
            </div>
            <div class="job-salary">
              <span><i class="fa fa-location-arrow"></i></span>
              <span>{{$job_offer->salary->Name}}</span>
            </div>
            <div class="job-tags">
              <span><i class="fa fa-location-arrow"></i></span>
              <div>
              </div>
               @foreach ($job_offer->tags as $item)
               {{($item->Name)}}
               @endforeach
            </div>
            <div class="jobs-social">
              <div class="social">
                <span class="social-divider"><i class="fa fa-search"></i></span>
                <span class="social-divider"><i class="fa fa-search"></i></span>
                <span class="social-divider"><i class="fa fa-search"></i></span>
                <span><i class="fa fa-search"></i></span>
              </div>
            </div>
          </div>
        </div>
        @endforeach
  
      {{-- </div> --}}
    </div>
   
    </div>
  </div>
</div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.js"
integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
crossorigin="anonymous">

</script>
<script>
 $(document).ready(function() {

        $('[data-search]').on('keyup', function () {
            var searchVal = $(this).val();
            var filterItems = $('[data-filter-item]');

            if (searchVal != '') {
                filterItems.addClass('hidden');
                $('[data-filter-item][data-filter-name*="' + searchVal.toLowerCase() + '"]').removeClass('hidden');
            } else {
                filterItems.removeClass('hidden');
            }
        });
        });
</script>



<script type="text/javascript">
// $(function() {

//             $('section').on('click', 'nav a', function(e) {
//                 e.preventDefault();

//                 // $('#load a').css('color', '#dfecf6');
//                 // $('#load').append('<img style="position: absolute; left: 0; top: 0; z-index: 100000;" src="/images/loading.gif" />');

//                 var url = $(this).attr('href');
//                 getArticles(url);
//                 window.history.pushState("", "", url);
//             });

//             function getArticles(url) {
//                 $.ajax({
//                     url : url
//                 }).done(function (data) {
//                     $('.articles').html(data);
//                 }).fail(function () {
//                     alert('Articles could not be loaded.');
//                 });
//             }
//         });
//   </script>
<input type="hidden" id="job_seeker" value="{{$job_seeker->id}}"> 
<input type="hidden" name="_token" value="{{ csrf_token() }}">


{{-- <script>
var id= $("#job_seeker").val();
var category=$('input[name=category]').val();
$.ajax({  
  url: '/job_seeker/{id}/show_offers',
  method:"POST",  
  data:{
   '_token': $('input[name=_token]').val(),
   'category':category
  },  
  success:function(data){  

  }  
});  
</script> --}}

<script>
  $(document).ready(function () {

var categories = [];

// Listen for 'change' event, so this triggers when the user clicks on the checkboxes labels

    
$('input[name="category[]"]').on('change', function (e) {
  var id=$('#job_seeker').val();
  var categorie_content = $(this).attr('data-categorie');
 
    e.preventDefault();
    categories = []; // reset 
    var category=[]
  

    
    $('input[name="category[]"]:checked').each(function()
    {
        categories.push($(this).val());
    });

   
    $('input[name="category[]"]:checked')
    {
      var isChecked = $(this).prop('checked');
      if(isChecked == false){
        
        // console.log($(this).attr('data-categorie'));
          // $('.jobs-category-selected').remove($(this));
        $('.jobs-category-selected li:contains("'+$(this).attr('data-categorie')+'")').remove();
          
        }
      category.push(categorie_content);
 
    };
    const postSummaries = category.map((post) => ({ id: $('input[name="category[]"]:checked').val(), title: $(this).attr('data-categorie')}));
   

    $.ajax({  
      url: '/job_seeker/{id}/show_offers',
      method:"POST",  
      data:{
      '_token': $('input[name=_token]').val(),
      'categories':categories,
      'job_seeker_id':id
      },
      success:function(data){  
        $('.jobs-render').html(data);
        $('.jobs-category-selected').append('<li>'+ postSummaries[0].title +'</li>  <i class="fa-thin fa-xmark"></i>');
        
      }  
    });  
    // $.post('/vacancies/searchcat', {categories: categories}, function(markup)
    // {
    //     $('#search-results').html(markup);
    // });            

});

});
</script>

@component('layouts.components.footer')

@endcomponent
@endsection
